name: Upload Data

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Upload
        uses: schmidlidev/runeql-tools/load_data@main
        env:
          INPUT: "/github/workspace/"
          MONGO_URI: ${{ secrets.MONGO_URI }}
